### PR TITLE
3. Center map based on user location

### PR DESCRIPTION
**Pull request by wardbeyens**

### CODE REVIEW

**Comment by jbelien** [comment]
Quick feedback (requested by @Driesvanransbeeck):

- When I accept to share my location (or when I search for a place), the map is only centered ; I think it also needs to zoom on your location (or the place your selected) ;
- Location is only shared on page load, I would add a button to give the possibility to share its "new" location (will be useful is the website is used on the go) ;
- What if the browser doesn't support the GeoLocation API ? That case doesn't seem to be handled ;
  ```js
  if('geolocation' in navigator) {
    /* geolocation is available */
  } else {
    /* geolocation IS NOT available */
  }
  ```

This (quick) feedback is only focused on GeoLocation.
But I also noticed stuff that doesn't mean anything in the French translation file.

**Comment by auloin** [comment]
Thanks @jbelien! We'll create separate issues for your first 2 suggestions. 

>    When I accept to share my location (or when I search for a place), the map is only centered ; I think it also needs to zoom on your location (or the place your selected) ;
> 
>    Location is only shared on page load, I would add a button to give the possibility to share its "new" location (will be useful is the website is used on the go) ;

**Comment by wardbeyens** [comment]
Zoom seems to work fine!

**Review by auloin — APPROVED** [review]

**Comment by wardbeyens** [comment]
closes #55

**Pull request merged**
